name: Build and Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:   
    - cron: '0 12 * * *'

jobs:
  build:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'
    - run: npm install      
    - run: npm test